/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SuccessTransferTransferIdLazyImport = createFileRoute(
  '/success-transfer/$transferId',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SuccessTransferTransferIdLazyRoute =
  SuccessTransferTransferIdLazyImport.update({
    id: '/success-transfer/$transferId',
    path: '/success-transfer/$transferId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/success-transfer.$transferId.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/success-transfer/$transferId': {
      id: '/success-transfer/$transferId'
      path: '/success-transfer/$transferId'
      fullPath: '/success-transfer/$transferId'
      preLoaderRoute: typeof SuccessTransferTransferIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/success-transfer/$transferId': typeof SuccessTransferTransferIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/success-transfer/$transferId': typeof SuccessTransferTransferIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/success-transfer/$transferId': typeof SuccessTransferTransferIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/success-transfer/$transferId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/success-transfer/$transferId'
  id: '__root__' | '/' | '/success-transfer/$transferId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SuccessTransferTransferIdLazyRoute: typeof SuccessTransferTransferIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SuccessTransferTransferIdLazyRoute: SuccessTransferTransferIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/success-transfer/$transferId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/success-transfer/$transferId": {
      "filePath": "success-transfer.$transferId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
